GET https://fso-phonebook-iopr.onrender.com/api/persons/

###
GET https://fso-phonebook-iopr.onrender.com/info/

###
GET https://fso-phonebook-iopr.onrender.com/api/persons/2

###
DELETE https://fso-phonebook-iopr.onrender.com/api/persons/2

###
POST https://fso-phonebook-iopr.onrender.com/api/persons
Content-Type: application/json

{
    "name": "Dan Petersons",
    "number": "+323434214"
}

###
GET https://fso-phonebook-iopr.onrender.com/api/persons/323432341

###
POST https://fso-phonebook-iopr.onrender.com/api/persons/ 
content-type: application/json

{
    "name": "Arto Hellas",
    "number": "040-123456"
}